# This workflow uses the common build and push Docker image workflow
name: Use Generic Build and Push

on:
  workflow_dispatch:  
jobs:
  generic-build-and-push:
    uses: nookyo/workflow-hub/.github/workflows/common-build-docker-image.yaml@main
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_TOKEN }}
    with:
      branch: main 
      build_command: "mvn clean package"
      dockerfile_path: "Dockerfile"
      docker_tags: "latest"
      push_image: true
