name: 'Dependency Review'
on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: bdeb5c67b738c9f2cb677af7c13af42bd172c1ac
          head-ref: ${{ github.ref }}
          show-openssf-scorecard: true
          vulnerability-check: true
          license-check: true
