name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set docker tags variable
        id: set_tags
        run: echo "docker_tags=$(echo ${GITHUB_REF} | sed -e 's|refs/tags/||' -e 's|refs/heads/||')" >> $GITHUB_ENV

      - name: Echo docker tags
        run: ${{ steps.set_tags.outputs.docker_tags }}
  
    outputs:
      docker_tags: ${{ steps.set_tags.outputs.docker_tags }}

  build-and-docker:
    needs: setup
    uses: nookyo/workflow-hub/.github/workflows/build-and-docker.yml@main
    with:
      maven_command: "clean package"
      dockerfile_path: "Dockerfile"
      docker_tags: ${{ needs.setup.outputs.docker_tags }}
      docker_image_name: qubership-integration-engine
      push_image: true
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_TOKEN }}
