# .github/workflows/main.yml
name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    uses: nookyo/workflow-hub/.github/workflows/docker-tag-template.yml 
   
  debug-docker-tags:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: docker tags
        run: echo "docker_tags = ${{ needs.setup.outputs.docker_tags }}"

  build-and-docker:
    needs: setup
    uses: nookyo/workflow-hub/.github/workflows/build-and-docker.yml@main
    with:
      maven_command: "clean package"
      dockerfile_path: "Dockerfile"
      docker_tags: ${{ needs.setup.outputs.docker_tags }}
      docker_image_name: qubership-integration-engine
      push_image: true
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_TOKEN }}
