name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup-tag:
    uses: nookyo/workflow-hub/.github/workflows/docker-tag-template.yml@main

  debug-docker-tag:
    runs-on: ubuntu-latest
    needs: setup-tag
    steps:
      - name: docker tags
        run: echo "docker_tag = ${{ needs.setup.outputs.docker_tag }}"

  build-app:
    needs: setup-tag
    uses: nookyo/workflow-hub/.github/workflows/build-app.yml@main
    with:
      artifact_name: qip-engine-jar
      artifact_path: target/qip-engine-*-exec.jar 
      maven_command: "clean package" 
    secrets:
      maven_username: ${{ secrets.OSSRH_USERNAME }}
      maven_password: ${{ secrets.OSSRH_TOKEN }}
	     
