name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    uses: nookyo/workflow-hub/.github/workflows/docker-tag-template.yml@main

  debug-docker-tags:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Debug docker_tags
        run: |
          if [ -z "${{ env.docker_tags }}" ]; then
            echo "Error: docker_tags is empty"
            exit 1
          fi
          echo "docker_tags = ${{ env.docker_tags }}"
        env:
          docker_tags: ${{ env.docker_tags }}

  build-and-docker:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use docker_tags for build
        run: |
          echo "Building with docker_tags=${{ env.docker_tags }}"
          # Здесь можно вставить команды сборки или вызов других reusable workflows
        env:
          docker_tags: ${{ env.docker_tags }}



