name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    uses: nookyo/workflow-hub/.github/workflows/docker-tag-template.yml@main

  debug-docker-tags:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Debug docker_tags from reusable workflow
        run: |
          if [ -z "${{ needs.setup.outputs.docker_tags }}" ]; then
            echo "Error: docker_tags is empty"
            exit 1
          fi
          echo "docker_tags = ${{ needs.setup.outputs.docker_tags }}"

  build-and-docker:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check docker_tags before build
        run: |
          if [ -z "${{ needs.setup.outputs.docker_tags }}" ]; then
            echo "Error: docker_tags is empty"
            exit 1
          fi
          echo "docker_tags = ${{ needs.setup.outputs.docker_tags }}"

      - name: Run build-and-docker workflow
        uses: nookyo/workflow-hub/.github/workflows/build-and-docker.yml@main
        with:
          maven_command: "clean package"
          dockerfile_path: "Dockerfile"
          docker_tags: ${{ needs.setup.outputs.docker_tags }}
          docker_image_name: qubership-integration-engine
          push_image: true
        secrets:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_TOKEN }}
