name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    uses: nookyo/workflow-hub/.github/workflows/docker-tag-template.yml@main

  debug-docker-tags:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: docker tags
        run: echo "docker_tags = ${{ needs.setup.outputs.docker_tags }}"
  build-app:
    needs: setup
    uses: nookyo/workflow-hub/.github/workflows/build-app.yml@main
    with:
      maven_command: "clean package" 