name: Main Workflow
on:
  workflow_dispatch:

jobs:
  call_first_workflow:
    uses: ./first-reusable.yml

  call_second_workflow:
    needs: call_first_workflow
    uses: ./second-reusable.yml
    with:
      example_input: ${{ needs.call_first_workflow.outputs.example_output }}
